export enum EIconName {
  Edit = 'edit',
  Delete = 'delete',
  Mail = 'mail',
  Location = 'location',
  Calendar = 'calendar',
  ChevronDown = 'chevron-down',
  Close = 'close',
  Search = 'search',
  MenuOpen = 'menu-open',
  Schema = 'schema',
  Settings = 'settings',
  AccountCircle = 'account-circle',
  Logout = 'logout',
}
